"""Pydantic schemas and domain models package."""

from backend.app.models.schemas import (
    AnalyzeRequest,
    AnalyzeURLRequest,
    AnalyzeURLResponse,
    BrandSimilarityInfo,
    EmailAnalyzeResponse,
    EmailAttachmentMeta,
    EmailHeaderAnalysis,
    ErrorDetail,
    ErrorResponse,
    ExtractedEntities,
    HealthResponse,
    HeuristicSignals,
    KnowledgeEvidence,
    NormalizedInput,
    OCRMetadata,
    ProcessingMetadata,
    ScreenshotAnalyzeResponse,
    Severity,
    ThreatIndicator,
    ThreatReport,
    ThreatType,
    URLIntelligenceReport,
    URLSignals,
)

__all__ = [
    "AnalyzeRequest",
    "AnalyzeURLRequest",
    "AnalyzeURLResponse",
    "BrandSimilarityInfo",
    "EmailAnalyzeResponse",
    "EmailAttachmentMeta",
    "EmailHeaderAnalysis",
    "ErrorDetail",
    "ErrorResponse",
    "ExtractedEntities",
    "HealthResponse",
    "HeuristicSignals",
    "KnowledgeEvidence",
    "NormalizedInput",
    "OCRMetadata",
    "ProcessingMetadata",
    "ScreenshotAnalyzeResponse",
    "Severity",
    "ThreatIndicator",
    "ThreatReport",
    "ThreatType",
    "URLIntelligenceReport",
    "URLSignals",
]
